services:
  detection_service:
    build: 
      context: ./detection_service
      dockerfile: Dockerfile
    container_name: ppe_detection_service
    env_file:
      - ./detection_service/.env
    volumes:
      - ./scenes:/app/scenes
      - ./source:/app/source
    environment:
      - SOURCE_DIR=/app/source/false1.mp4
      - RISKY_DIR=/app/scenes
      - REDIS_HOST=redis_service
    networks:
      - vision_network
    depends_on:
      - redis_service

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # restart: unless-stopped

  redis_service:
    image: redis:alpine
    container_name: ppe_redis
    networks:
      - vision_network
    volumes:
      - redis_data:/data
    
volumes:
  redis_data:
networks:
  vision_network:
    driver: bridge